version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: node index.js
    ports:
      - 80:80
  json:
    build:
      context: .
      dockerfile: dockerfile.json
    command: json-server --watch db.json
    volumes:
      - ./json:/usr/src/app/
    ports:
      - 3000:3000